/*
 * This file is generated by jOOQ.
 */
package com.hafnium.supplychaintree.jooq.tables.references


import com.hafnium.supplychaintree.jooq.tables.Edge



/**
 * The table <code>public.edge</code>.
 */
val EDGE: Edge = Edge.EDGE
