### Get the whole tree starting at nodeId
GET {{host}}/api/tree/from/1

### Create a new tree edge
POST {{host}}/api/edge/from/1/to/2

### Delete an existing tree edge
DELETE {{host}}/api/edge/from/1/to/2

### Generate a large test tree
POST {{host}}/api/tree/from/1000?size=1000
