@fromNodeId=1
@toNodeId=2

### Get the whole tree starting at nodeId
GET {{host}}/api/tree/from/{{fromNodeId}}

### Create a new tree edge
POST {{host}}/api/edge/from/{{fromNodeId}}/to/{{toNodeId}}

### Delete an existing tree edge
DELETE {{host}}/api/edge/from/{{fromNodeId}}/to/{{toNodeId}}
