# Common configuration properties for all profiles/environments

spring:
  application:
    name: supply-chain-tree
  jooq:
    sql-dialect: POSTGRES

  profiles:
    active: default

server:
  error:
    include-message: always
  compression:
    enabled: true
    mime-types: application/json
