# Common configuration properties for all profiles/environments

spring:
  application:
    name: supply-chain-tree
  jooq:
    sql-dialect: POSTGRES

server:
  compression:
    enabled: true
    mime-types: application/json
